
\version "2.24.3"
\language "english"
		\new Staff \with {
				  midiInstrument="acoustic grand"
				  \clef bass
				  } {
				 <<
  				 { < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c f c' ds' f' gs' b' >4 < c e c' d' f' g' b' >4 < b, e b d' f' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, e b d' e' g' as' >4 < b, ds b d' e' g' as' >4 < b, ds b cs' e' fs' as' >4 < as, ds as cs' e' fs' a' >4 < as, ds as cs' ds' fs' a' >4 < as, ds as cs' ds' fs' a' >4 < as, ds as cs' ds' fs' a' >4 < as, ds as cs' ds' fs' a' >4 < as, d as cs' ds' fs' a' >4 < as, d as c' ds' f' a' >4 < a, d a c' ds' f' gs' >4 < a, d a c' ds' f' gs' >4 < a, d a c' d' f' gs' >4 < a, d a c' d' f' gs' >4 < a, cs a c' d' f' gs' >4 < a, cs a b d' e' gs' >4 < gs, cs gs b d' e' g' >4 < gs, cs gs b d' e' g' >4 < gs, cs gs b cs' e' g' >4 < gs, c gs as cs' ds' g' >4 < gs, c gs as cs' ds' g' >4 < g, c g as cs' ds' fs' >4 < g, c g as cs' ds' fs' >4 < g, b, g as c' ds' fs' >4 < g, b, g a c' d' fs' >4 < fs, b, fs a c' d' f' >4 < fs, as, fs a c' d' f' >4 < fs, as, fs gs b cs' f' >4 < fs, as, fs gs b cs' f' >4 < f, as, f gs b cs' e' >4 < f, a, f gs b cs' e' >4 < f, a, f g as c' e' >4 < f, a, f g as c' e' >4 < e, gs, e g as c' ds' >4 < e, gs, e fs as b ds' >4 < e, gs, e fs a b ds' >4 < ds, g, ds fs a b d' >4 < ds, g, ds f a as d' >4 < ds, fs, ds f gs as d' >4 < d, fs, d e gs a cs' >4 < d, fs, d e gs a cs' >4 < d, f, d e gs a cs' >4 < cs, f, cs ds g gs c' >4 < cs, e, cs ds g gs c' >4 < cs, e, cs ds g gs c' >4 < c, e, c d fs g b >4 < c, ds, c d fs g b >4 < b,, ds, b, cs f fs as >4 < b,, d, b, cs f fs as >4 < as,, d, as, c f f a >4 < as,, cs, as, c e f a >4 < as,, cs, as, b, e e a >4 < a,, c, a, b, ds e gs >4 < a,, c, a, as, ds ds gs >4 < gs,, b,, gs, as, ds ds g >4 < gs,, b,, gs, a, d d g >4 < g,, as,, g, a, d d fs >4 < g,, as,, g, gs, cs cs fs >4 < fs,, a,, fs, gs, cs cs f >4 < fs,, a,, fs, g, c c f >4 < f,, gs,, f, g, c c e >4 < f,, g,, f, fs, c b, e >4 < e,, g,, e, fs, b, b, ds >4 < e,, fs,, e, f, b, as, ds >4 < ds,, fs,, ds, e, as, a, d >4 < ds,, f,, ds, e, as, a, d >4 < d,, e,, d, ds, a, gs, cs >4 < d,, e,, d, ds, a, gs, cs >4 < cs,, ds,, cs, d, gs, g, c >4  }
 				 >>
		}