
\version "2.24.3"
\language "english"
		\new Staff \with {
				  midiInstrument="acoustic grand"
				  } {
				 <<
  				 { < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c f c' ds' f' gs' b' > < c e c' d' f' g' b' > < c e c' d' f' g' b' > < b, e b d' f' g' as' > < b, e b d' f' g' as' > < b, e b d' f' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, e b d' e' g' as' > < b, ds b d' e' g' as' > < b, ds b cs' e' fs' as' > < b, ds b cs' e' fs' as' > < b, ds b cs' e' fs' as' > < as, ds as cs' e' fs' a' > < as, ds as cs' e' fs' a' > < as, ds as cs' e' fs' a' > < as, ds as cs' e' fs' a' > < as, ds as cs' ds' fs' a' > < as, d as cs' ds' fs' a' > < as, d as cs' ds' fs' a' > < as, d as c' ds' f' a' > < as, d as c' ds' f' a' > < as, d as c' ds' f' a' > < a, d a c' ds' f' gs' > < a, d a c' ds' f' gs' > < a, cs a c' ds' f' gs' > < a, cs a c' ds' f' gs' > < a, cs a b ds' e' gs' > < a, cs a b d' e' gs' > < a, cs a b d' e' gs' > < a, cs a b d' e' gs' > < gs, c gs b d' e' g' > < gs, c gs b d' e' g' > < gs, c gs as d' ds' g' > < gs, c gs as d' ds' g' > < gs, c gs as d' ds' g' > < gs, c gs as cs' ds' g' > < gs, b, gs as cs' ds' g' > < g, b, g as cs' ds' fs' > < g, b, g a cs' d' fs' > < g, b, g a cs' d' fs' > < g, as, g a cs' d' fs' > < g, as, g a cs' d' fs' > < g, as, g a cs' d' fs' > < fs, as, fs gs c' cs' f' > < fs, as, fs gs c' cs' f' > < fs, a, fs gs c' cs' f' > < fs, a, fs gs c' cs' f' > < fs, a, fs g c' c' f' > < f, a, f g c' c' e' > < f, gs, f g b c' e' > < f, gs, f g b c' e' > < f, gs, f fs b b e' > < e, g, e fs b b ds' > < e, g, e fs b b ds' > < e, g, e fs as b ds' > < e, g, e f as as ds' > < e, fs, e f as as ds' > < ds, fs, ds f as as d' > < ds, fs, ds e as a d' > < ds, f, ds e as a d' > < ds, f, ds e a a d' > < d, f, d e a a cs' > < d, e, d ds a gs cs' > < d, e, d ds a gs cs' > < d, e, d ds gs gs cs' > < cs, ds, cs d gs g c' > < cs, ds, cs d gs g c' >  }
 				 >>
		}